### ISSUE TITLE
Undocumented feature?

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#11]
How to create icons in menu? There's nothing about it in docs.

(examples of what I mean)
Example from MageAIO ezreal
![image](https://github.com/badspacebar/sdk/assets/141168740/b19344cd-f3d4-4a10-b89e-1cf06826c1e2)

Example from GGAIO ezreal
![image](https://github.com/badspacebar/sdk/assets/141168740/8eaf82a4-c143-4907-b5aa-fb9b7d7c4a91)

**Comment by badspacebar** [comment]
```
local myIcon = graphics.sprite('XXX/menu_icon.png')
myMenu.example_slider:set('icon', myIcon)
```
