### ISSUE TITLE
Additional explantions?

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#13]
It isn't very clear what some of the fields in pred_input are for such as boundingRadiusMod, boundingRadiusModTarget, boundingRadiusModSource, dashRadius (used in annie q example). Also are there more fields we could enter? There isn't a definitive list so it's hard to tell as I can only go by examples given and see what was used in them.

**Comment by badspacebar** [comment]
That maybe all, you already know
