### ISSUE TITLE
damagelib doesn't calculate xerath R correctly

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#22]
damagelib.get_spell_damage('XerathRMissileWrapper', 3, player, obj, false, 0) doesn't take into account his stacks damage

**Comment by 69sinisterblade69** [comment]
Im going to add it here instead of making new issue. 
damagelib.get_spell_damage('YasuoE', 2, player, obj, false, 0) returns garbage damage (65584152576) when yasuo have "YasuoDashScalar" buff.

**Comment by badspacebar** [comment]
XerathR damage, fixed now
