### ISSUE TITLE
new vec functions not working 

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#23]
v1:countAllies(range)
v1:countEnemies(range)
v1:countAllyLaneMinions(range)
v1:countEnemyLaneMinions(range)
![image](https://github.com/badspacebar/sdk/assets/141168740/7184d740-1084-4766-bff7-69caab6c18f0)

v1:isUnderEnemyTurret()
v1:isUnderAllyTurret()
![image](https://github.com/badspacebar/sdk/assets/141168740/4907f7a1-6263-451b-9782-94c08261173d)

It seems that all those functions expect some userdata, and not number/nothing like documentation suggests. As far as I can tell it happens to both vec2 and vec3 variants.

**Comment by badspacebar** [comment]
all fixed
