### ISSUE TITLE
Item icons - player:inventorySlot(0).icon

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#25]
```player:inventorySlot(0).icon``` returns nil while ```player:inventorySlot(0).iconName``` seem to return correct value. It's not a big deal for active items like zhonya because I can use ```player:spellSlot(6).icon``` but for other items like Guardian Angel for example I can't do that. Also tried ```player:inventorySlot(0).item.icon``` but it didn't work. 

How should I get icons of items?

**Comment by badspacebar** [comment]
will be fixed in patch 20231225
