### ISSUE TITLE
Item cooldown and passives on enemies not working

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#26]
```hero:spellSlot(6).cooldown``` works properly if used on player, but doesn't if checked on an enemy. I've confirmed that cb.spell is registering that cast (of for example zhonya or any other active item), but aforementioned cooldown doesn't change.

**Comment by 69sinisterblade69** [comment]
Same thing happens with passives with cooldown, like blitz or anivia, tried using `hero:spellSlot(63).cooldown` and cd doesnt work, but icon/name does.

**Comment by badspacebar** [comment]
Fixed now
