### ISSUE TITLE
graphics draw

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#27]
What does `graphics.set_draw(enabled)` `graphics.get_draw()` `graphics.set_draw_menu(enabled)` are supposed to do? From my testing `graphics.get_draw()` always returns nil. I would've thought that `graphics.set_draw(enabled)` can disable/enable all draws or something like that, but changing it doesn't have any effect, same thing with `graphics.set_draw_menu(enabled)`.

**Comment by badspacebar** [comment]
`graphics.set_draw(false)`  will be fixed in 20231225
