### ISSUE TITLE
Check if hero is winding up 

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#29]
Is it possible to check if player/hero is winding up? As far as I checked you can't do it with `orb.core.can_attack()`  `orb.core.can_action()` (and other currently documented features) because you technically still can action while winding up, it's just that doing so will cancel your aa.

**Comment by badspacebar** [comment]
I think `orb.core.can_attack()` is enough
you can also check `orb.core.cur_attack_start_client`/ `orb.core.cur_attack_start_server`
and `player:attackDelay()` `player:attackCastDelay(64)`

**Comment by 69sinisterblade69** [comment]
As I've said in previous message, `orb.core.can_attack()` wouldn't work because it still returns true even when attacking will cancel your previous aa. Thankfully other dev have told me about `orb.core.is_winding_up_attack()`, which as far as I tested worked exactly how I wanted, though I could probably achieve the same result with the method you mentioned.

**Comment by badspacebar** [comment]
more docs added now, please let me know if there is something missing
