### ISSUE TITLE
orb target (lane clear and combo)

### ISSUE THREAD

**Issue by 69sinisterblade69** [badspacebar/sdk#31]
I want to get orb current laneclear target but docs say that `orb.farm.clear_target` is deprecated. Is there any alternative for that? btw is there any way to get orb current target in combo?

**Comment by badspacebar** [comment]
clear_target is still available

**Comment by 69sinisterblade69** [comment]
Then if it's fine to use the deprecation message from docs should be deleted. 

Also about orb target in combo, other dev have told me about `orb.combat.get_target()`, which works fine.

**Comment by badspacebar** [comment]
more docs added now, please let me know if there is something missing
